### ISSUE TITLE
[Errno 2] No such file or directory: 'masscan.json'

### ISSUE THREAD

**Issue by zzggtt** [7dog7/masscan_to_nmap#1]
您好，在安装中，masscan版本里你说：Centos 安装 Masscan (版本GIT version: 1.0.5-86-ga025970,版本低会导致-oJ masscan.json格式出现偏差导致报错)
clone下载最新的为什么还是有这个错误呢？
大佬能方便看一下吗

**Comment by 7dog7** [comment]
您好，如果出现[Errno 2] No such file or directory: 'masscan.json',说明你masscan没执行到，看下代码的masscan路劲,或者根据readme.md重新再来一次哈
