### ISSUE TITLE
i am got error

### ISSUE THREAD

**Issue by Stakingsoup** [7dog7/masscan_to_nmap#2]
helllo Sir i am got error 
whats wrong??
![Screenshot_2020-08-18-16-27-06-09](https://user-images.githubusercontent.com/58569784/90496361-ece0db00-e16f-11ea-8a3c-3712c78026d2.jpg)

**Comment by 7dog7** [comment]
Masscan version - OJ causes ，Version: 1.0.5 is recommended

**Comment by 7dog7** [comment]
Version: 1.0.4 is - OJ format is different

**Comment by Stakingsoup** [comment]
solved
