### ISSUE TITLE
ImportError: No module named nmap

### ISSUE THREAD

**Issue by qianxun0** [7dog7/masscan_to_nmap#3]
你好，在pip install -r requirements.txt后满足所有所需模块，在配置完成后，开始运行脚本会提示没有nmap模块，这是什么原因导致的呢？
![image](https://user-images.githubusercontent.com/43699132/94354415-51675200-00ad-11eb-8d67-21f30aac8390.png)

**Comment by 7dog7** [comment]
yum install nmap与python-nmap请根据文档，安装nmap与依赖

**Comment by fayewong00** [comment]
![image](https://user-images.githubusercontent.com/51317315/97098616-ba94b200-16b9-11eb-96fc-5b5744b361b2.png)
楼主，已经安装了nmap，和python-nmap，请问还需要其他设置吗?也是提示没有nmap模块

**Comment by 7dog7** [comment]
先yum install nmap后执行pip install python-nmap如果还是出现此问题，建议python -m pip install python-nmap
