### ISSUE TITLE
BUG   使用xshell运行完回车无法换行

### ISSUE THREAD

**Issue by TryA9ain** [7dog7/masscan_to_nmap#4]
Ctrl+c 后再回车也不能换行
![image](https://user-images.githubusercontent.com/51145610/94406485-ad60d200-01a4-11eb-8b58-75886bb96fe2.png)
![image](https://user-images.githubusercontent.com/51145610/94406575-d2554500-01a4-11eb-9e30-9a85db65abc6.png)

**Comment by 7dog7** [comment]
这个应该不是代码问题。

**Comment by snow0715** [comment]
这个就是代码问题

**Comment by 7dog7** [comment]
知识盲区有时间再研究一下

**Comment by snow0715** [comment]
我测试了一下，使用的是python3，nmap和多线程应该是有冲突的，测试代码如下，注释掉锁的话是多线程运行，会出现无法换行且输入命令不显示的BUG，加上锁单线程运行的话，则不会出现BUG

def NmapScan(i):
    #lock.acquire()
    nm = nmap.PortScanner()
    ret = nm.scan("120.132.132.132", "443", arguments='-Pn,-sS')
    print(nm)
    #lock.release()

for i in range(5):
    t = threading.Thread(target=NmapScan, args=(i,))
    t.start()

**Comment by 7dog7** [comment]
监听KeyboardInterrupt应该可以解决。

**Comment by snow0715** [comment]
> Ctrl+c 后再回车也不能换行 ![image](https://user-images.githubusercontent.com/51145610/94406485-ad60d200-01a4-11eb-8b58-75886bb96fe2.png) ![image](https://user-images.githubusercontent.com/51145610/94406575-d2554500-01a4-11eb-9e30-9a85db65abc6.png)

测试了一下，出现这种情况的原因是因为在上面我的示例代码中执行了“stty echo”命令，导致输入被隐藏且回车不换行，我的解决方法是使用.sh文件来执行python脚本，其内容为：
a.sh
python scan.py
stty -echo
这样可以规避掉该问题，至于代码层面的措施尚未研究

**Comment by 7dog7** [comment]
emmm我个人使用都是screen很久才出现一次。我觉得不影响使用。
